const enStrings = {
  "titleNotice": "Notice",
  "splashSlogan": "Hoc Cung Thuan",
  "titleGrammar": "Grammar",
  "titleVocabulary": "Vocabulary",
  "titlePractice": "Practice",
  "tv_finish_practice": "Finish",
  "tv_submit_practice": "Submit",
  "titleSuccessPractice": "Great!",
  "msgSuccessPractice": "You got all the questions right. Great!",
  "tv_recheck": "review",
  "back_to_home": "go to home",
  "title_topic_vocabulary": "Topic vocabulary",
  "title_you_learned_vocabulary": "You learned %1s word",
  "title_review_word": "Review %1s words",
  "title_topic": "Topic",
  "title_target_vocabulary": "Your target today",
  "title_learn_words_everyday": "Learn %1s words",
  "mode_normal_vocabulary": "Normal (5 words)",
  "mode_hard_vocabulary": "Hard (10 words)",
  "mode_challenge_vocabulary": "Challenge (15 words)",
  "title_mode_vocabulary": "Challenge Mode",
};