const viStrings = {
  "titleNotice": "Thông báo",
  "splashSlogan": "Hoc Cung Thuan",
  "titleGrammar": "Ngữ pháp thông dụng",
  "titleVocabulary": "Từ vựng",
  "titlePractice": "Luyện tập",
  "tv_finish_practice": "Hoàn thành",
  "tv_submit_practice": "Hoàn thành",
  "titleSuccessPractice": "Xin Chúc mừng!",
  "msgSuccessPractice": "Bạn đã đúng tất cả các câu hỏi. Tuyệt vời!",
  "tv_recheck": "Xem lại",
  "back_to_home": "Thoát",
  "title_topic": "Học theo chủ đề",
  "title_topic_vocabulary": "Chủ đề từ vựng",
  "title_you_learned_vocabulary": "Bạn đã học được %1s từ",
  "title_review_word": "Ôn tập %1s từ",
  "title_target_vocabulary": "Mục tiêu hôm nay",
  "title_learn_words_everyday": "Học %1s từ mỗi ngày",
  "mode_normal_vocabulary": "Cơ bản (5 từ)",
  "mode_hard_vocabulary": "Nâng cao (10 từ)",
  "mode_challenge_vocabulary": "Thử thách (15 từ)",
  "title_mode_vocabulary": "Chọn thử thách",
};